-- Create USERS table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='USERS' AND xtype='U')
CREATE TABLE USERS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(255) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL
);

-- Create TASKS table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TASKS' AND xtype='U')
CREATE TABLE TASKS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Insert test data
IF NOT EXISTS (SELECT * FROM USERS WHERE USERNAME = 'admin')
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin', 'admin123');

IF NOT EXISTS (SELECT * FROM USERS WHERE USERNAME = 'test')
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('test', 'test123');
